snailpet
========
Software for head Nodding Adjustment in Interfile Listmode data for Positron Emission Tomography

---------------
Description
---------------

Positron emission tomography (PET) is used in medicine to image the distribution of molecules in the body. Body motion during a PET scan have a negative effect on the images. 
This python package snailpet aims to improve image quality by data-driven motion corrections, with a focus on head movements. 
Functionality

.. _LOR  http://tech.snmjournals.org/content/29/1/4.full
- read and write interfile data 
- apply standard corrections (normalisation, deadtime, radial arc, randoms subtraction)
- gate data, into frames with less motion
- estimate position and translation motion by tracking Center of Mass
- motion correction event by event that preserves LOR_ directions for coincidences
- listmode reconstruction

Intended use

.. _PETLink  https://www.siemens-healthineers.com/en-us/molecular-imaging/petlink-documents
- Listmode data in the PETLink_ format, from the Siemens Biograph mCT PET scanner, model 1104.  
- I will use 
     * the scanner software to convert into interfile format
     * do my motion corrections and output interfile
     * and finally do image reconstruction with scanner software.
     
------------------
How to install
------------------

------------
How to use
------------


This is part of my master's thesis in medical engineering at KTH.
.. author:: Hugo Linder

