snailpet
============

Software for head Nodding Adjustment in Interfile Listmode data for Positron Emission Tomography

----------------
description
----------------
This branch is a toy version of the larger project, where I want to familiarize myself with organizing the project, before commiting a lot of code to this new structure. 

I want to:
  have a base, which I can use as a simple example of a project, as reference.
  practice pytest, import, style check, subpackages, and setup. 
  go through development to actual package. Furthermore I want to practice using git. 

---------------
how to install
---------------

git clone https://github.com/hugolinder/snailpet.git

-------------
how to use
-------------
- python -c "import project_tutorial; project_tutorial.test()"
- run example in a notebook demonstrating the package. 

----------------
References
----------------
.. _tutorial https://dev.to/codemouse92/dead-simple-python-project-structure-and-imports-38c6

- inspired by packages odl, odlpet, stir
- a tutorial_ "Dead Simple Python: Project Structure and Imports" 
